// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreManagement.Data;

namespace StoreManagement.Data.Migrations
{
    [DbContext(typeof(TablesDbContext))]
    [Migration("20200925163239_TablesDbContextMigration")]
    partial class TablesDbContextMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StoreManagement.Models.tblFirma", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFillimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataMbarimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPageses")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmriFirmes")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<bool>("Paguar")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("firma");
                });

            modelBuilder.Entity("StoreManagement.Models.tblKategorite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdFirma")
                        .HasColumnType("bigint");

                    b.Property<string>("LlojiKategorise")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("kategorite");
                });

            modelBuilder.Entity("StoreManagement.Models.tblPorosite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataPorosise")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdFirma")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotaliCmimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotaliSasise")
                        .HasColumnType("int");

                    b.Property<decimal>("TotaliZbritjeve")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WorkerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("porosite");
                });

            modelBuilder.Entity("StoreManagement.Models.tblProduktet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Barkodi")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataProdhimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSkadimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmriProduktit")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<long>("IdFirma")
                        .HasColumnType("bigint");

                    b.Property<long>("IdKategoria")
                        .HasColumnType("bigint");

                    b.Property<int>("Sasia")
                        .HasColumnType("int");

                    b.Property<int>("SasiaEShitur")
                        .HasColumnType("int");

                    b.Property<decimal>("Zbritja")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("produktet");
                });
#pragma warning restore 612, 618
        }
    }
}
