// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreManagement.Data;

namespace StoreManagement.Data.Migrations
{
    [DbContext(typeof(TablesDbContext))]
    [Migration("20201114235437_addtblScannerAndThermaledit2")]
    partial class addtblScannerAndThermaledit2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StoreManagement.Models.tblFirma", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFillimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataMbarimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPageses")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmriFirmes")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("NrKategorive")
                        .HasColumnType("int");

                    b.Property<int>("NrProdukteve")
                        .HasColumnType("int");

                    b.Property<int>("NrUseraveWorkers")
                        .HasColumnType("int");

                    b.Property<bool>("Paguar")
                        .HasColumnType("bit");

                    b.Property<bool>("RuatjaTotalitPer12Mujorin")
                        .HasColumnType("bit");

                    b.Property<bool>("RuatjaTotalitPer6Mujorin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("firma");
                });

            modelBuilder.Entity("StoreManagement.Models.tblKategorite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdFirma")
                        .HasColumnType("bigint");

                    b.Property<string>("LlojiKategorise")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("kategorite");
                });

            modelBuilder.Entity("StoreManagement.Models.tblKonfigurimet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryNumbers")
                        .HasColumnType("int");

                    b.Property<int>("LimitAdminsCompany")
                        .HasColumnType("int");

                    b.Property<int>("LimitWorkersForCompany")
                        .HasColumnType("int");

                    b.Property<int>("ProductNumber")
                        .HasColumnType("int");

                    b.Property<int>("YearsForPayment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("konfigurimet");
                });

            modelBuilder.Entity("StoreManagement.Models.tblPorosite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DhjetorTotali")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GushtTotali")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("IdFirma")
                        .HasColumnType("bigint");

                    b.Property<decimal>("JanarTotali")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KorrikTotali")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MajTotali")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MarsTotali")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NentorTotali")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrillTotali")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QershorTotali")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShkurtTotali")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShtatorTotali")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TetorTotali")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("porosite");
                });

            modelBuilder.Entity("StoreManagement.Models.tblProduktet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barkodi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataProdhimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSkadimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmriProduktit")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<long>("IdFirma")
                        .HasColumnType("bigint");

                    b.Property<long>("IdKategoria")
                        .HasColumnType("bigint");

                    b.Property<string>("OtherInformation1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInformation2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInformation3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sasia")
                        .HasColumnType("int");

                    b.Property<int>("SasiaEShitur")
                        .HasColumnType("int");

                    b.Property<decimal>("Zbritja")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("produktet");
                });

            modelBuilder.Entity("StoreManagement.Models.tblScannerAndThermal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CuponQrCode")
                        .HasColumnType("nvarchar(18)")
                        .HasMaxLength(18);

                    b.Property<string>("DeviceModel")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<long>("IdFirma")
                        .HasColumnType("bigint");

                    b.Property<long>("ScannerKey")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Vat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VendorId")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ScannerAndThermal");
                });
#pragma warning restore 612, 618
        }
    }
}
